### ISSUE TITLE
Doesn't work with small windows

### ISSUE THREAD

**Issue by aalekseyev** [aspiers/smooth-scrolling#13]
Scrolling is not smooth when the number of lines in the window is smaller than 2*smooth-scroll-margin. This issue is solved as a part of PR #10, but it's a separate issue. I have a stand-alone fix for this in https://github.com/aalekseyev/smooth-scrolling.

**Comment by aspiers** [comment]
Belated thanks for this report!  I think I'll probably end up just merging #10, although currently having problems testing it :-(

**Comment by aspiers** [comment]
Now that I've merged #10, please can you confirm this is fixed?

**Comment by aalekseyev** [comment]
I've not tested it, but it's very likely that it's fixed.

**Comment by aspiers** [comment]
OK, please reopen if you discover it's still a problem :)
