### ISSUE TITLE
C-v and M-v break smooth-scroll-margin

### ISSUE THREAD

**Issue by evorion** [aspiers/smooth-scrolling#16]
After C-v and M-v it is possible for point to end up within smooth-scroll-margin which, by definition, breaks smooth-scroll-margin functionality.

**Comment by aspiers** [comment]
I can only reproduce this when the point was already within `smooth-scroll-margin` *before* pressing `C-v` or `M-v` - is that what you mean?  In that case I think that might be the best behaviour.  If you mean something else, please could you provide a minimal test case?  Thanks!

**Comment by evorion** [comment]
For me it doesn't matter where the point was before either M-v or C-v. After either one the point ends up either on the first (C-v) or the last (M-v) line. If I use C-n or C-p after the point ended up on the first or the last line respectively, the margin setting kicks back in and the text gets scrolled smooth-scroll-margin lines with the point ending up where you'd expect it to be.

**Comment by aspiers** [comment]
I can't reproduce this, sorry.  I'm guessing it's some kind of issue with your setup.  Please can you provide a minimal test case starting with `emacs -Q`?

**Comment by evorion** [comment]
First of all thank you for your amazing dedication to FOSS. I appreciate it very much. Here is my -Q session:

~ emacs -Q

(dotimes (i 100)
  (print "Just a line"))C-j

M-x
load-file
~/.emacs.d/elpa/smooth-scrolling-20160227.1715/smooth-scrolling.el

(require 'smooth-scrolling)C-j
smooth-scrolling

(smooth-scrolling-mode 1)C-j
t

(setq smooth-scroll-margin 5)C-j
5

M-<
C-v

# MY POINT IS ON THE FIRST VISIBLE LINE AFTER THIS

M->
M-v

# MY POINT IS ON THE LINE BEFORE THE LAST VISIBLE ONE AFTER THIS

Debian stable, Emacs 24.4.1

**Comment by aspiers** [comment]
Thanks, I can reproduce with this!  Very weird!  @DarwinAwardWinner do you have any idea what's going on here?  Since your major rewrite I'm not as familiar with how it all works ...

**Comment by DarwinAwardWinner** [comment]
I just pushed a commit that fixes this to my repo. I just had to add `scroll-up-command` and `scroll-down-command` to the list of commands to be smooth-scroll-ized.

**Comment by DarwinAwardWinner** [comment]
Thinking about it some more, it might be possible to just put the smooth scroll logic into `post-command-hook` and have it work for every command without having to enumerate all the commands which might do scrolling. I'll look into it.

**Comment by aspiers** [comment]
Amazing, thanks a lot Ryan!  I'm still confused why my normal emacs setup doesn't experience this issue though...

**Comment by DarwinAwardWinner** [comment]
Maybe you already found the problem several months ago, and then added those lines to your config and then forgot about it?

**Comment by aspiers** [comment]
Nope, my repo is what's on github :)

**Comment by DarwinAwardWinner** [comment]
Ok, after trying the `post-command-hook` trick, it doesn't work, because there are definitely some commands, like C-l and scrolling the window, where do don't want to do smooth scrolling. So it looks like having the whitelist like it does now is the right solution.
