### ISSUE TITLE
C-v M-v not show margin

### ISSUE THREAD

**Issue by Pitometsu** [aspiers/smooth-scrolling#19]
### Environment

- Emacs 24.5.2
- Linux (both Xorg and tty versions)
- `smooth-scrolling` 93005218f9cd4bcc1a80943cb630355231090c81

### Steps to reproduce

- enable plugin (even in emacs  -Q)
- press C-v (scroll-up-command) few times
- press M-v (scroll-down-command) few times
- *bug:* (bad UX) scrolling stop at some margin, and with M-v user can't reach begin of the buffer.
- but begin of the buffer can be reached by `M-<` or `M-g-g 0` or just by repeating `<up>`

**Comment by aspiers** [comment]
Thanks for the report, but AFAICS this is the intended behaviour - even without the plugin installed, vanilla `emacs -Q` exhibits this behaviour, where `M-v` will not necessarily reach the beginning of the buffer and `C-v` the end.  If I'm misunderstanding something please let me know and I'll reopen.

**Comment by Pitometsu** [comment]
@aspiers hm, not sure is it intended or no, but previously, without `smooth-scrolling`, never have such user experience, and without it reaching working just fine (surely, without margins). Maybe, I should ask it as a special feature request (make scrolling able reach begin/end of the buffer despite margins).

**Comment by aspiers** [comment]
I don't understand - please can you explain the exact difference in behaviour between `emacs -Q` and `emacs -Q` with `smooth-scrolling` loaded?

**Comment by Pitometsu** [comment]
Even with custom number in `scroll-margin` it works fine.

**Comment by Pitometsu** [comment]
Example:

***

On the left side with `scroll-margin`, on right -- with `smooth-scrolling`.
![Step 1](http://i.imgur.com/c6tQVcO.png)
Then press `PgDn`
![Step 2](http://i.imgur.com/xGIRqmD.png)
Then press `PgUp`
![Step 3](http://i.imgur.com/l1vhkVa.png)
That's it: `smooth-scrolling` driven buffer can't now reach begin of the buffer by repeating `PgUp` keystroke.

**Comment by aspiers** [comment]
Thanks a lot, that's very helpful. I'm about to go travelling so I can't promise I'll be able to look at it any time soon. Although if you're lucky, maybe @DarwinAwardWinner or someone else will :-)

**Comment by Pitometsu** [comment]
@aspiers up to you for sure. Anyway, thanks for your attention and have a nice trip ;-)

**Comment by aspiers** [comment]
Thanks :)

**Comment by DarwinAwardWinner** [comment]
Ok, I figured out why this happens. Basically, every time you hit page up, Emacs scrolls the window to the top of the buffer, but doesn't move the point. Then smooth-scrolling-mode scrolls the window back down again. I'll submit a PR with a fix.
